added Travis CI support
microsoft/PowerBI-visuals-sampleCorrPlotRVisual pull request #1
Opened 2017-04-10 13:39 UTC by mvgaliev

2017-04-11 10:03 UTC, ignatvilesov requested changes
Could you please include a ```.gitignore``` file with the following content:
```
node_modules
.tmp
dist
.api
*.log
```

Please also include the [npm start](https://github.com/Microsoft/PowerBI-visuals-AsterPlot/blob/master/package.json#L13) command to the ```package.json```.

2017-04-11 16:06 UTC, ignatvilesov requested changes
Could you please remove the ```.api``` directory and try to execute ```npm install```. As a result you will have a few changes that you have to commit.

2017-04-12 10:45 UTC, ignatvilesov approved these changes

2017-04-12 11:43 UTC, AviSander approved these changes

2017-04-12 11:43 UTC, merged